#=========================================================================
# OpenRAM SRAM Compiler 
#=========================================================================
# Author : Kavya Somasi 
# Date   : April 19, 2022
#

name: custom_dc_scripts

#-------------------------------------------------------------------------
# Outputs
#-------------------------------------------------------------------------

outputs:
  - generate-results.tcl 

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - cp generate-results.tcl           outputs/generate-results.tcl
