#=========================================================================
# Constraints
#=========================================================================
# Author : Kavya Somasi 
# Date   : March 31, 2022
#

name: constraints

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - constraints.tcl

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
#  clock_period: 1.0
  design_name: undefined

commands: 
  - cat cpu_isle.sdc > outputs/constraints.tcl
