#=========================================================================
# Providing dummy ARC RAM libraries 
#=========================================================================
# Author : Kavya Somasi
# Date   : March 31, 2022
#

name: arc_ram_lib

#-------------------------------------------------------------------------
# Outputs
#-------------------------------------------------------------------------

outputs:
  - arc_rams.lib
  - arc_rams.db

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - cp arc_rams.lib outputs/arc_rams.lib
  - cp arc_rams.db  outputs/arc_rams.db

